### ISSUE TITLE
PIK Intercom

### ISSUE THREAD

**Issue by termit0s** [alryaz/hass-pik-intercom#25]
В последних версиях HA переход на python 3.11
Не работает интеграция:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pik_intercom/__init__.py", line 363, in async_setup_entry
    done, pending = await asyncio.wait(
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

**Comment by alryaz** [comment]
Укажите версию компонента. Указанный код в описании ошибки отсутствует в актуальной версии компонента.
