### ISSUE TITLE
Интеграция сломана для HA 2023.12.1

### ISSUE THREAD

**Issue by oprokidnev** [alryaz/hass-pik-intercom#30]
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pik_intercom/__init__.py", line 363, in async_setup_entry
    return_when=asyncio.FIRST_EXCEPTION,
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 425, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
    ```

**Comment by alryaz** [comment]
Сегодня поправлю

**Comment by oprokidnev** [comment]
@alryaz сорри, не до конца правильно понял процесс. Интеграция ожила после обновления до последней версии. Однако, произошла ошибка миграции.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 650, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pik_intercom/__init__.py", line 455, in async_migrate_entry
    async_change_device_prefix(
  File "/config/custom_components/pik_intercom/helpers.py", line 225, in async_change_device_prefix
    if first_part == DOMAIN and second_part.startswith(from_prefix):
```

**Comment by alryaz** [comment]
> @alryaz сорри, не до конца правильно понял процесс. Интеграция ожила после обновления до последней версии. Однако, произошла ошибка миграции.
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 650, in async_migrate
>     result = await component.async_migrate_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/pik_intercom/__init__.py", line 455, in async_migrate_entry
>     async_change_device_prefix(
>   File "/config/custom_components/pik_intercom/helpers.py", line 225, in async_change_device_prefix
>     if first_part == DOMAIN and second_part.startswith(from_prefix):
> ```

Ошибка скопирована не полностью

**Comment by alryaz** [comment]
@oprokidnev С какой версии Вы обновлялись?

**Comment by oprokidnev** [comment]
@alryaz актуальную для HA 2023.3.4
